language: ruby
cache: bundler
sudo: false
services:
  - postgresql
  - mysql

install:
- bundle install
before_script:
- psql -c 'create database scoped_search_test;' -U postgres
- mysql -e 'create database scoped_search_test;'
script:
- bundle exec rake

rvm:
- "2.6.0"
- "2.7.1"

gemfile:
- Gemfile.activerecord52
- Gemfile.activerecord52_with_activesupport52
- Gemfile.activerecord60
- Gemfile.activerecord60_with_activesupport60
- Gemfile.rails_master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
  exclude:
    - rvm: "2.7.1"
      gemfile: Gemfile.activerecord52
    - rvm: "2.7.1"
      gemfile: Gemfile.activerecord52_with_activesupport52
